# Site settings
title: 100 Days of Developer eXperience 
description: Daily unfiltered & opinionated post on DX starting 14th July 2019
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://100daysDX.com" 

# User settings
username: 100 Days of Developer eXperience
user_description: Jarkko "APItalist" Moilanen
user_title: Daily unfiltered & opinionated post on DX starting 14th July 2019
email: jarkko@vimo.fi
twitter_username: Jarkko_Moilanen
github_username:  kyyberi
disqus_username: jarkkomoilanen

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 10


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Suggested topics
    url: /topics
  - title: Tags
    url: /tags
  - title: About Me & site
    url: /about
  - title: Literature
    url: /literature
  - title: Testimonials
    url: /testimonials


# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
